### PR TITLE
method of `walk!` for `GridSpaceSingle`

### LINKED ISSUE #718: walk! in GridSpaceSingle with GridAgentis is missing a method
**Describe the bug**
A simple Agent on a GridSpaceSingle cannot be modified using the walk!(agent, rand, model) function.

Within the walk! function, `ids_in_position` is called and an error appears as such:

```
ERROR: MethodError: no method matching ids_in_position(::Tuple{Int64, Int64}, ::AgentBasedModel{GridSpaceSingle{2, true}, GridAgent{2}, Agents.Schedulers.Randomly, Nothing, TaskLocalRNG})
Closest candidates are:
  ids_in_position(::Union{Int64, Tuple{Int64, Int64, Float64}, Tuple{Vararg{Int64, N}}, Tuple{Vararg{var"#s5", M}} where var"#s5"<:AbstractFloat} where {N, M}, ::AgentBasedModel{<:GridSpace}) at ~/.julia/packages/Agents/JVXgR/src/spaces/grid_multi.jl:243
  ids_in_position(::Union{Int64, Tuple{Int64, Int64, Float64}, Tuple{Vararg{Int64, N}}, Tuple{Vararg{var"#s5", M}} where var"#s5"<:AbstractFloat} where {N, M}, ::GridSpace) at ~/.julia/packages/Agents/JVXgR/src/spaces/grid_multi.jl:244
  ids_in_position(::A, ::Any) where A<:AbstractAgent at ~/.julia/packages/Agents/JVXgR/src/spaces/discrete.jl:49
```

It appears that there is no method defined for ids_in_position for a model of type GridSpaceSingle, only for GridSpace

**Minimal Working Example**

```
model = ABM(GridAgent{2}, GridSpaceSingle((5,5)))

add_agent!(model)

agent_step!(agent, model) = walk!(agent, rand, model)

step!(model, agent_step!)   # error on this line
```

**Agents.jl version**
v5.6.2

### PR DESCRIPTION
**Pull request by JaydevSR**
Fixes #718

### CODE REVIEW

**Comment by JaydevSR** [comment]
@Datseris is this mergeable?

**Comment by Datseris** [comment]
Hello, apologies for forgetting about this. Please add one additional test in the test suite that confirms that indeed this PR solves #718. You may add this test in this file: https://github.com/JuliaDynamics/Agents.jl/blob/main/test/grid_space_tests.jl 

In addition, please move the definition of this function to the GridSpaceSingle file, as this function is only for that space.

**Comment by JaydevSR** [comment]
@Datseris added tests and fixed the function to make sure it works as expected (earlier I actually didn't pay attention to the constraints of GridSpaceSingle)

**Comment by JaydevSR** [comment]
@Datseris is there anything else that needs to be added?

File: src/spaces/grid_single.jl [hunk 1]
```diff
@@ -110,3 +110,15 @@ function nearby_ids(
...
 end
+
+# Method for walking on GridSpaceSingle, similar to `walk!` in spaces/utilities.jl
+function walk!(
+    agent::AbstractAgent,
+    direction::NTuple{D,Int},
+    model::ABM{<:GridSpaceSingle}
+) where {D}
+    target = normalize_position(agent.pos .+ direction, model)
+    if id_in_position(target, model) == 0 # if target unoccupied
```
Comment (Datseris) [inline src/spaces/grid_single.jl:121]:
```suggestion
    if isempty(target, model) # if target unoccupied
```

please use the API function here instead of manually checking.

**Review by Datseris — APPROVED** [review]
Yes, looks good, I only did a minor change.
