### PR TITLE
OSMSpace Serialization

### LINKED ISSUE #496: Model (De)Serialization
Points to consider:
- What should the target API look like? I think it should just be two functions `save` and `load` (names are of course up for debate)
- What format should it be saved in? JLD2, or using `Serialization` from stdlib (See the example at the bottom)? It might be worth testing if one is significantly faster than the other, or results in smaller files. I also saw `BSON.jl`, so maybe that's a possibility?
- This ties in to the previous point: Should the serialized file be able to be viewed without having to load it in as a model? Or is the sole purpose of this feature to load and save, and have the file be completely opaque? I'm in favour of the first option, although it would require some additional effort
- In some cases (GraphSpace and OSMSpace) multiple save files may be required. How should this be handled?
- Should the pathfinding extensions be implemented first, in case there's additional data to be saved or a change in the data layout?

I've gone through all the structs that would need to be saved, and mapped it out:

Properties to save:
- `ABM.agents` # Possibly as a dataframe-esque format, since the dictionary can be reconstructed from that and it may make viewing easier
- `ABM.space`
- `ABM.properties` # The structure and contents of this are unknown, so ideally it should load back to the exact same state it was
- `ABM.rng` # Each RNG struct would have it's own internal state, so it can resume from the same point in the sequence
- `ABM.maxid`
- `GridSpace.metric`
- `GridSpace.hoods`
- `GridSpace.hoods_tuple`
- `GridSpace.pathfinder`
- `ContinuousSpace.grid`
- `ContinuousSpace.dims`
- `ContinuousSpace.spacing`
- `ContinuousSpace.extent`
- `GraphSpace.graph` # `JuliaGraphs/GraphIO.jl` exists, but it saves to a separate file. I don't think there's a point in reinventing the wheel, so there's the possibility of having multiple save files to consider
- `OSMSpace.m`    # A quick glance at `pszufe/OpenStreetMapX.jl` didn't show any functions to save to a .osm file
- `AStar.agent_paths` # This is a Dict mapping to Linked List. Not difficult to implement, but worth exploring if the linked list state can be preserved or if it will have to be regenerated from an array
- `AStar.grid_dims`
- `AStar.neighborhood` # just save Pathfinder.diagonal_movement
- `AStar.admissibility`
- `AStar.walkable`
- `AStar.cost_metric` # HeightMap is recursive

Properties taken from user at deserialization:
- `ContinuousSpace.update_vel!`
- `ABM.scheduler`
What if we save a symbol, and assume the function exists in the environment when it is loaded?

Properties reconstructed from saved data:
- `GridSpace.s`
- `GraphSpace.s`
- `OSMSpace.s`
Agents store their positions, so these structures can be regenerated at deserialization

A serialization method that @Libbum found. It uses Serialization from the standard library, so there isn't any additional dependency. However, it's completely opaque. At a glance it seems to work. I'm currently testing if it saves the more intricate data listed above
```julia
using Agents
using Serialization # stdlib

(model, agent_step!, model_step!) = Models.predator_prey(   
               n_wolves = 40,   
               n_sheep = 60,   
               dims = (25, 25),   
               Δenergy_sheep = 5,   
               Δenergy_wolf = 13,   
               sheep_reproduce = 0.2,   
               wolf_reproduce = 0.1,   
               regrowth_time = 20,   
           )

serialize("model.bin", model)
# Exit julia, restart
using Agents
model = deserialize("model.bin")
```

### LINKED ISSUE #513: OSM.random_road_position and OSM.random_route! are not reproducible
**Describe the bug**
Both these functions are not reproducible since they use `generate_point_in_bounds` from OSMX, which doesn't use the model RNG.

**Minimal Working Example**
Zombies example. Two runs lead to different positions for some agents, which are ones that had a new path generated

**Agents.jl version**
4.3

### PR DESCRIPTION
**Pull request by AayushSabharwal**
Closes #496, Closes #513

The agent position and destination lat/lon are stored in `SerializableOSMSpace`. During deserialization, these values are used to update the corresponding agent fields.

### CODE REVIEW

**Comment by AayushSabharwal** [comment]
Currently agent routes are rendered meaningless when it loads back in. From what I understand, there isn't really a way to recalculate them since there isn't a way to know what keywords were passed to `plan_route` to calculate it. The only other solution I can think of is to save all the intersections by converting them to lat/lon.

It might also be a good idea to deepcopy each agent and clear the routes vector before saving, to save on space

**Comment by AayushSabharwal** [comment]
`OSMSpace` serialization works now. There's some overhead with having to convert between indexes and lat/lon during serialization and deserialization, but that seems unavoidable. Currently there's unnecessary space saved for agent routes in the model, when they're unnecessary and recalculated during deserialization anyway. I think that should be avoidable with a shallow copy during serialization, and clearing the `agent.route`

File: src/submodules/io/jld2_integration.jl [hunk 1]
```diff
@@ -75,6 +75,7 @@ struct OSMAgentPositionData
     id::Int
     pos::NTuple{2,Float64}
     dest::NTuple{2,Float64}
+    route::Vector{NTuple{2,Float64}}
```
Comment (Libbum) [inline src/submodules/io/jld2_integration.jl:78]: Is this necessary? Why can we not just re-recreate it on-load?

Comment (AayushSabharwal) [reply src/submodules/io/jld2_integration.jl:78]: Can it be determined whether the route was :shortest or :fastest? Or if it was a return route? If so, it's not necessary.

Comment (AayushSabharwal) [reply src/submodules/io/jld2_integration.jl:78]: Also, for `:fastest`, the speeds would need to be provided

**Comment by AayushSabharwal** [comment]
There's a flaw in the implementation, which I'm working on fixing

**Comment by AayushSabharwal** [comment]
Is OSMX deterministic with indexes of intersections? In other words, if I load the same map twice is intersection 565 the same in both? It appears to be so in a quick test, but that invalidates the need for any special serialization code

File: src/submodules/io/jld2_integration.jl (hunk 1 above)
Comment (Libbum) [reply src/submodules/io/jld2_integration.jl:78]: Ah, yes - I see. That needs to be added as a property somewhere probably.

Worry that I have is that the indexes in the route are not transferable due to the OSMX structure, so even adding lat/lon here it means that we'd need to make an additional bunch of methods to re-embed some synthetic route. 

Without the route type property stored that'll be a problem in general, so may make sense to consider that extension somehow. 

Bah, but this could be a per-agent property.... A bit to think about here. 

Feel free to go ahead in the direction you're taking here and we'll see if you hit a wall or not, then we can figure out if there's a simpler design.

**Comment by Libbum** [comment]
> Is OSMX deterministic with indexes of intersections? In other words, if I load the same map twice is intersection 565 the same in both? It appears to be so in a quick test, but that invalidates the need for any special serialization code

No. That's the issue.

It's the same on your machine with your julia version. Change to 1.5 and it wont work, send the file to me and I can't load it.

**Comment by AayushSabharwal** [comment]
Ah. I get it. This complicates things a little, but I have an idea

**Comment by AayushSabharwal** [comment]
This seems to work. As of now:
- Agent positions are saved as a 3-tuple, where the first two values are the lat/lon of the corresponding intersection and the third field is identical to `OSMAgent.pos[3]`. Similarly for destination
- Routes are saved as a vector of lat/lon of the corresponding intersections

**Comment by Libbum** [comment]
Alright. 

To actually review this, can you make an example using the `OSM.TEST_MAP` with a few agents on paths that you generate, save the file and email it to me. I'll load it up, plot the paths and you tell me if your model is the same.

**Comment by AayushSabharwal** [comment]
There doesn't seem to be a way to easily shallow copy agents without the user having defined `copy` for that type. `deepcopy` is still an option, but it could potentially be a lot slower

**Comment by Libbum** [comment]
> There doesn't seem to be a way to easily shallow copy agents without the user having defined copy for that type. deepcopy is still an option, but it could potentially be a lot slower

Indeed. There isn't one. For collection, [we tell them to be mindful](https://github.com/JuliaDynamics/Agents.jl/blob/29fb63fd05a7c14a9d17c6aade6a520368c6bc56/src/simulations/collect.jl#L97) about that. Do you think there needs to be documentation here as well?

**Comment by AayushSabharwal** [comment]
I'm only looking into it to avoid storing `agent.route` since it's redundant data. It works perfectly without it, albeit with a larger file size. I have an idea with some metaprogramming magic which I'll try out

**Comment by AayushSabharwal** [comment]
This reduces file size, and tests seem to pass locally

**Comment by AayushSabharwal** [comment]
I expected it to merge as a single commit, but I guess this works too. Squash and merge should compress it all into one in the end.

File: docs/src/index.md [hunk 2]
```diff
@@ -10,6 +10,7 @@ To get started, please read the [Tutorial](@ref) page.
 
 !!! tip "Latest news: Agents.jl v4.3"
       * New functions `dump_to_csv` and `populate_from_csv!` to save and load agent data to and from CSV files
+      * New functions `save_checkpoint` and `load_checkpoint` to save and load entire models to and from files
```
Comment (Libbum) [inline docs/src/index.md:13]: Since this is new functionality outside of what we've already implemented, we will have to release 4.4. So this section needs to be updated accordingly.

File: src/submodules/io/jld2_integration.jl [hunk 3]
```diff
@@ -80,42 +91,63 @@ struct SerializableAStar{D,P,M}
...
 end
 
-to_serializable(t::ABM) = SerializableABM(
-    collect(values(t.agents)),
-    to_serializable(t.space),
-    to_serializable(t.properties),
-    t.rng,
-    t.maxid.x,
-)
+function to_serializable(t::ABM{S}) where {S}
```
Comment (Libbum) [inline src/submodules/io/jld2_integration.jl:94]: A lot of this section should use helper functions from [here](https://github.com/JuliaDynamics/Agents.jl/blob/22076028a00cc24ac619567627967bcd76c97268/src/core/model.jl#L218-L230).

`nagents(model)` vs `length(sabm.agents)`
`allagents(model)` vs `values(t.agents)`

etc.

**Review by Libbum — APPROVED** [review]
Once those comments are resolved, bump the changelog and it's good for a merge/release.

**Review by Datseris — APPROVED** [review]
Agree with Tim!

**Comment by AayushSabharwal** [comment]
I'll merge once CI finishes

**Comment by Datseris** [comment]
We will need a new "update message", which will need to be done via Scratch.jl before we release, c.f. #493  (this needs to be done in a separate PR)

**Comment by AayushSabharwal** [comment]
Sure. I'll spend some time going through Scratch.jl and open a PR with the changes

**Comment by AayushSabharwal** [comment]
50% 🥳
